-- ASSENTRA UPGRADE MIGRATION

-- 1. ADD NEW COLUMNS TO ASSETS TABLE
ALTER TABLE assets ADD COLUMN IF NOT EXISTS qr_code VARCHAR(500);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS qr_value VARCHAR(100);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS purchase_date DATE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS last_service_date DATE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS repair_count INTEGER DEFAULT 0;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS last_used_date DATE;

-- 2. CREATE AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    action VARCHAR(100),
    asset_id INTEGER REFERENCES assets(id),
    description TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. CREATE EXIT CHECKLIST TABLE
CREATE TABLE IF NOT EXISTS exit_checklists (
    id SERIAL PRIMARY KEY,
    employee_id INTEGER REFERENCES users(id),
    asset_id INTEGER REFERENCES assets(id),
    status VARCHAR(50) DEFAULT 'Pending'
);
